Rebased sources version 0.2

diff --git a/src/Linux-configure-hostname-Deploy-FDZ b/src/Linux-configure-hostname-Deploy-FDZ
--- a/src/Linux-configure-hostname-Deploy-FDZ
+++ b/src/Linux-configure-hostname-Deploy-FDZ
@@ -1,7 +1,7 @@
 # ############################################
-# Linux-generalize-network-Capture-FDZ
+# Linux-configure-hostname-Deploy-FDZ
 # Version: 0.5
-#############################################
+# ############################################
 # (c) Copyright 2017 Hewlett Packard Enterprise Development LP
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -13,84 +13,111 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
-#The output of the following guestfish echo commands goes
-# into the Golden Image Activity log file.
+# The output of the following 4 guestfish echo commands goes
+# to the OS-Volume Activity log.
 echo "======================================="
-echo "Linux-generalize-network-Capture-FDZ"
+echo "Linux-configure-hostname-Deploy-FDZ"
 echo "======================================="
+echo "\tManual configuration of /etc/hostname"
 
-# Create a temporary directory in the Image Streamer
-!mkdir new_network
-
-
-# The output of the following guestfish command goes
-# in the Golden Image Activity log file.
-echo " Copy out the network directory"
-
-# Depending on the OS-Type, push-out the entire network directory
-# to the just created new_network directory in the Image Streamer.
-<!awk '/sles/ {print "copy-out /etc/sysconfig/network/ new_network/"} ; /rhel/ || /centos/ || /xen/ {print "copy-out /etc/sysconfig/network-scripts new_network/"}' ./OS-Type
-
-# Create a bash script in the Golden Image that will be 
-# pushed-out to the Image Streamer before execution.
-upload -<<END /temp/ImageStreamer/gen_network_conf 
-#!/bin/bash
-
-OS_Type=$(cat OS-Type)
-case $OS_Type in
- rhel|centos|xen*)
- NET_DIR="network-scripts"
- ;;
- sles)
- NET_DIR="network"
- ;;
- *)
- echo "OS Type $OS_Type not supported. Exiting. " 
- exit 1 
- ;;
-esac
- 
-net_cfg_files=`ls new_network/$NET_DIR/ | grep "ifcfg-"`
-
-for net_cfg_file in $net_cfg_files
-do
-	if [ $net_cfg_file != "ifcfg-lo" ]
-	then
-		rm -rf new_network/$NET_DIR/$net_cfg_file 
-		echo -e "\tNetwork interface cfg file $net_cfg_file successfully removed!!!" 
-	fi
-done
-exit 0
+# The following guestfish upload command populates
+# the OS-Volume /etc/hostname file.
+upload -<<END /etc/hostname
+@HostName@.@DomainName@
 END
 
-# Push-out the above script before execution in the Image Streamer
-download /temp/ImageStreamer/gen_network_conf ./gen_network_conf
-!source ./gen_network_conf
+# The output of the following guestfish echo command goes in the
+# OS-Volume Activity log file.
+echo "\tEdit /etc/sysconfig/network file to set the HOSTNAME variable"
+
+# The following guestfish upload command populates the 
+# OS-Volume network file. In case of SUSE, we will get an error
+# because /etc/sysconfig/network is a directory already present. 
+# Hence we add the "-" to the upload command to avoid a
+# bad exit of guestfish.
+-upload -<<END /etc/sysconfig/network
+#This file has been altered by Image Streamer.
+NETWORKING=yes
+HOSTNAME=@HostName@.@DomainName@
+END
 
 # The output of the following guestfish echo command goes
-# in the Golden Image Activity log file.
-echo " Removal of the Golden Image network directory"
+# in the OS-Volume Activity log file.
+echo "\tPreparation of the script that will add the right entry in /etc/hosts" 
 
-# Remove the Golden Image network directory 
-# depending on the OS-Type.
-<!awk '/sles/ {print "rm-rf /etc/sysconfig/network"} ; /rhel/ || /centos/ || /xen/ {print "rm-rf /etc/sysconfig/network-scripts"}' ./OS-Type
+# The following bash script goes in the OS-Volume /temp/configure-hosts file.
+# It will be executed during next reboot 
+upload -<<END /temp/configure_hosts
+#!/bin/bash
 
-# Pull-in the cleaned network directory into the Golden Image
-# at the right location depending on the OS-Type.
-echo " Pull-in the cleaned network directory into the Golden Image" 
-<!awk '/sles/ {print "copy-in new_network/network/ /etc/sysconfig/ "} ; /rhel/ || /centos/ || /xen/ {print "copy-in new_network/network-scripts/ /etc/sysconfig"}' ./OS-Type
+# This script requires the /temp/interface_names file generated by the
+# Linux-configure-multiple-NICs plan script. 
 
+# The output of the following echo command (name of this script)
+# goes into the OS log file (i.e. /var/log/messages).
+echo "Entering ${0}..."
 
-# Various clean up in the Golden Image.
-# The output of the guestfish echo commands goes
-# in the Golden Image Activity log file.
-echo " Remove /etc/init.d/ibftT if exists"
--rm-rf /etc/init.d/ibftT
+if [ ! -f /temp/interface_names ]; then
+ echo -e '\tCould not find file /temp/interface_names.
+\tThis script must be launched after the NICs configuration.
+\tCannot update /etc/hosts with hostname. Exiting...'
+ exit 2
+fi
 
-echo " Remove SSH host keys"
--glob rm-rf /etc/ssh/ssh_host_*
+# This script requires all the NICs operational.
+# However, the execution time of this script during the
+# boot process is not predictable because launched asynchronously by rc.local.
+# We will wait until NICs are configured and exit after a timeout.
 
+echo "Adding a hostname record in /etc/hosts if possible"
+let timeout=60
+let i=1
+ifaces=`cat /temp/interface_names`
+echo "Interface_names: $ifaces"
+#rm -f /temp/interface_names
+read -r -a array <<< $ifaces
+iface=${array[0]}
 
-echo -e " Clear the resolv.conf file"
-upload -<<END /etc/resolv.conf
+while [ $i -lt $timeout ] ; do
+ ip_address=`ip a list $iface | awk '/inet / {split($2, array, "/" ); print array[1]}' `
+ if [ -z $ip_address ] ; then
+ #echo "Length of ip_address is still 0"
+ sleep 1
+ let ++i
+ else
+ break
+ fi
+done
+
+# Remove this script and exit if timeout is reached, 
+if [ -z $ip_address ] ; then
+ echo "Could not retrieve the IPv4 addresse of $iface. Exiting"
+ # The following command deletes the current script.
+ unlink $0
+ exit 2
+fi
+
+# The output of the following echo command goes
+# in the OS log file. Typically /var/log/messages.
+echo "populating /etc/hosts with $ip_address (found after $i seconds..)."
+
+fqdn=@HostName@.@DomainName@
+alias=$(echo ${fqdn%%.*} )
+sed -i "/::1/a\\$ip_address $fqdn $alias" /etc/hosts
+sed -i "/::1/a\\#This file has been altered by Image Streamer." /etc/hosts
+
+# The output of the following bash command goes in 
+# the OS log file. Typically /var/log/messages.
+echo "Exting ${0}..."
+
+# The following command deletes the current script
+unlink $0
 END
+
+# The output of the following guestfish command goes
+# in the OS-Volume Activity log file.
+echo "Add the generated configure_hosts script to the RC file to run at boot time."
+
+# The following Image Streamer echo command appends
+# a line in the already present RC file.
+!echo "sh /temp/configure_hosts" >> ./RC-FILE
diff --git a/src/Linux-configure-multiple-NICs-Deploy-FDZ b/src/Linux-configure-multiple-NICs-Deploy-FDZ
--- a/src/Linux-configure-multiple-NICs-Deploy-FDZ
+++ b/src/Linux-configure-multiple-NICs-Deploy-FDZ
@@ -1,7 +1,7 @@
-# ############################################
-# Linux-generalize-network-Capture-FDZ
-# Version: 0.5
-#############################################
+# #############################################
+# Linux-configure-multiple-NICs-Deploy-FDZ
+# Version 0.7
+# #############################################
 # (c) Copyright 2017 Hewlett Packard Enterprise Development LP
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -13,84 +13,293 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
-#The output of the following guestfish echo commands goes
-# into the Golden Image Activity log file.
+# The following echo commands are performed by the guestfish shell.
+# Their output is present in the OS-Volume Activity log file.
 echo "======================================="
-echo "Linux-generalize-network-Capture-FDZ"
+echo "Linux-configure-multiple-NICs-Deploy-FDZ"
 echo "======================================="
 
-# Create a temporary directory in the Image Streamer
-!mkdir new_network
+# The following echo command is performed by the guestfish shell.
+# Its output is present in the OS-Volume Activity log file.
+echo "\tPrepare network configuration script to be executed at next reboot"
+
+# The following command creates a bash script in the OS-Volume.
+# This script will be called at next reboot by the RC file
+# It configures the NICs given its arguments of the command line ($1, $2...).
+
+# The output of the echo commands present in the following script goes
+# in the operating system log file. Typically /var/log/messages.
+# use the following command to view them once the OS-Volume 
+# has been deployed and booted:
+# grep rc.local /var/log/messages
+
+upload -<<END /temp/NIC-configure
+#! /bin/bash
+echo "Entering NIC-configure ..."
+
+net_mac=$1
+vlan=$2
+net_ip=$3
+net_gw=$4
+net_domain=$5
+dns1=$6
+dns2=$7
+netmask=$8
+
+mask2cidr() {
+ nbits=0
+ IFS=.
+ for dec in $1 ; do
+ case $dec in
+ 255) let nbits+=8;;
+ 254) let nbits+=7;;
+ 252) let nbits+=6;;
+ 248) let nbits+=5;;
+ 240) let nbits+=4;;
+ 224) let nbits+=3;;
+ 192) let nbits+=2;;
+ 128) let nbits+=1;;
+ 0);;
+ *) echo -e "\tError: $dec is not recognised"; exit 1
+ esac
+ done
+ echo "$nbits"
+}
 
 
-# The output of the following guestfish command goes
-# in the Golden Image Activity log file.
-echo " Copy out the network directory"
-
-# Depending on the OS-Type, push-out the entire network directory
-# to the just created new_network directory in the Image Streamer.
-<!awk '/sles/ {print "copy-out /etc/sysconfig/network/ new_network/"} ; /rhel/ || /centos/ || /xen/ {print "copy-out /etc/sysconfig/network-scripts new_network/"}' ./OS-Type
-
-# Create a bash script in the Golden Image that will be 
-# pushed-out to the Image Streamer before execution.
-upload -<<END /temp/ImageStreamer/gen_network_conf 
-#!/bin/bash
-
-OS_Type=$(cat OS-Type)
+# Retrieve OS-Type and set OS-Type dependent variables.
+OS_Type=$(cat /temp/OS-Type)
 case $OS_Type in
- rhel|centos|xen*)
+ rhel|centos)
  NET_DIR="network-scripts"
+ RC_FILE="rc.local" 
  ;;
  sles)
  NET_DIR="network"
+ RC_FILE="after.local" 
  ;;
  *)
- echo "OS Type $OS_Type not supported. Exiting. " 
- exit 1 
+ echo "OS Type not supported. Exiting. "
+ exit 1
  ;;
 esac
- 
-net_cfg_files=`ls new_network/$NET_DIR/ | grep "ifcfg-"`
 
-for net_cfg_file in $net_cfg_files
+
+# Check the presence of Netwok Manager only on RHEL and CentOS:
+if [ "$OS_Type" == "rhel" -o "$OS_Type" == "centos" ] ; then 
+ echo -e "\tChecking presence of NetworkManager..."
+ if [[ ! $(systemctl -t service --all | grep NetworkManager.service) ]] ; then
+ echo -e "\tNetworkManager not installed; Exiting..."
+ exit 2
+ fi
+
+ if [[ $(systemctl start NetworkManager.service) ]] ; then
+ echo -e “\tCould not start NetworkManager. Exiting...”
+ exit 3
+ fi
+fi
+
+
+echo -e "\tCheck the matching interface name for $net_mac."
+interfaces=`ls /sys/class/net/`
+echo 'echo $interfaces'
+echo $interfaces
+
+for iface in $interfaces
 do
-	if [ $net_cfg_file != "ifcfg-lo" ]
-	then
-		rm -rf new_network/$NET_DIR/$net_cfg_file 
-		echo -e "\tNetwork interface cfg file $net_cfg_file successfully removed!!!" 
-	fi
+ mac=`cat /sys/class/net/$iface/address`
+ if [ ${mac,,} == ${net_mac,,} ]
+ then
+ interface_name=$iface
+ echo $interface_name >> /temp/interface_names
+ fi
 done
+
+# Print the list of found interface names for debug purposes.
+echo "cat /temp/interface_names"
+cat /temp/interface_names
+
+if [ "$OS_Type" == "rhel" -o "$OS_Type" == "centos" ] ; then
+ echo -e "\tCheck if NetworkManager is still running; Who knows...."
+ if [[ $(systemctl --quiet is-failed NetworkManager.service) ]] ; then
+ echo -e “\tNetworkManager not running. Exiting”
+ exit 4
+ fi
+ echo -e "\tNetworkManager up and running."
+fi
+
+# If no IP address supplied, configure NIC with DHCP.
+# Remember that $net_ip is the third arg ($3).
+
+case $OS_Type in
+ rhel|centos)
+if [[ -z $net_ip ]]
+then
+ if [ $vlan -ne 0 ];then
+ echo "Configure $interface_name for DHCP"
+ nmcli connection add type vlan con-name $interface_name$vlan ifname $interface_name.$vlan id $vlan dev $interface_name
+ else
+ nmcli connection add con-name $interface_name ifname $interface_name type ethernet autoconnect yes
+ fi
+else
+ echo "Configure $interface_name for static."
+
+ if [ $vlan -ne 0 ];then
+ nmcli connection add type vlan con-name $interface_name$vlan ifname $interface_name.$vlan id $vlan dev $interface_name ip4 $net_ip/$(mask2cidr $netmask) gw4 $net_gw
+ else
+ nmcli con add con-name $interface_name ifname $interface_name type ethernet autoconnect yes ip4 $net_ip/$(mask2cidr $netmask) gw4 $net_gw
+ fi
+
+cat <<CONF>/etc/resolv.conf
+# Generated by Image Streamer
+search $net_domain
+nameserver $dns1
+nameserver $dns2
+CONF
+fi
+ ;;
+sles)
+if [[ -z $net_ip ]]
+then
+echo "Configure $interface_name for DHCP"
+cat <<CONF>/etc/sysconfig/network/ifcfg-$interface_name
+#This file has been created by Image Streamer.
+NAME="$interface_name"
+DEVICE="$interface_name"
+BOOTPROTO="dhcp"
+STARTMODE=auto
+CONF
+
+else
+
+echo "Configure $interface_name for static."
+cat <<CONF>/etc/sysconfig/network/ifcfg-$interface_name
+#This file has been created by Image Streamer.
+NAME="$interface_name"
+DEVICE="$interface_name"
+BOOTPROTO="static"
+STARTMODE=auto
+IPADDR="$net_ip"
+NETMASK="$netmask"
+CONF
+
+cat <<CONF>/etc/resolv.conf
+#This file has been modified by Image Streamer.
+search $net_domain
+nameserver $dns1
+nameserver $dns2
+CONF
+
+cat <<CONF>/etc/sysconfig/network/routes
+#This file has been modified by Image Streamer.
+default $gateway - -
+CONF
+
+fi
+ ;;
+*)
+ echo "OS Type $OS_Type not supported. Exiting"
+ exit 1
+ ;;
+esac
+
+
+echo "Exiting NIC-configure."
 exit 0
 END
 
-# Push-out the above script before execution in the Image Streamer
-download /temp/ImageStreamer/gen_network_conf ./gen_network_conf
-!source ./gen_network_conf
 
-# The output of the following guestfish echo command goes
-# in the Golden Image Activity log file.
-echo " Removal of the Golden Image network directory"
+# The following 2 echo commands are executed by the guestfish shell.
+# Their output goes in the OS-Volume Activity log.
+echo "\tPrepare the script that will populate the RC-FILE with the NICs configuration commands."
+echo "\tThe number of NICs to configure is automatically calculated using the Network Custom Attributes of this Plan Script ."
+# TODO: Offer the possibility to configure less NICs than present in the profile.
 
-# Remove the Golden Image network directory 
-# depending on the OS-Type.
-<!awk '/sles/ {print "rm-rf /etc/sysconfig/network"} ; /rhel/ || /centos/ || /xen/ {print "rm-rf /etc/sysconfig/network-scripts"}' ./OS-Type
+# The following command creates a bash script in the OS-Volume. 
+# This script will be copied-out to the Image Streamer and executed their.
+# Its goal is to generate all the necessary entries in the RC-FILE for each NIC 
+# that has to be configured.
+# NOTE: The Custom Attributes are expanded during the creation of the script.
+upload -<<END /temp/ImageStreamer/network-configuration
+#! /bin/bash
 
-# Pull-in the cleaned network directory into the Golden Image
-# at the right location depending on the OS-Type.
-echo " Pull-in the cleaned network directory into the Golden Image" 
-<!awk '/sles/ {print "copy-in new_network/network/ /etc/sysconfig/ "} ; /rhel/ || /centos/ || /xen/ {print "copy-in new_network/network-scripts/ /etc/sysconfig"}' ./OS-Type
+# Retrieve OS-Type and set OS-Type dependent variables.
+OS_Type=$(cat OS-Type)
+case $OS_Type in
+ rhel|centos)
+ NET_DIR="network-scripts"
+ RC_FILE="rc.local" 
+ ;;
+ sles)
+ NET_DIR="network"
+ RC_FILE="after.local" 
+ ;;
+ *)
+ echo "OS Type not supported. Exiting. "
+ exit 1
+ ;;
+esac
 
 
-# Various clean up in the Golden Image.
-# The output of the guestfish echo commands goes
-# in the Golden Image Activity log file.
-echo " Remove /etc/init.d/ibftT if exists"
--rm-rf /etc/init.d/ibftT
+# Compute the number of Ethernet NICs to configure.
+# Limitation: This simple compute method exits when the first "not connected" NIC
+# is found. Hence, if subsequent NICs are connected, they will not be
+# configured. 
+let n=0
+for NIC in @NIC1.mac@ @NIC2.mac@ @NIC3.mac@ @NIC4.mac@ ; do
+ if [ "$NIC" == "none" ]; then
+ break
+ fi
+ let n++
+ NICs_count=$n
+ echo -e "\tNumber of NICs to configure: $NICs_count"
+done
 
-echo " Remove SSH host keys"
--glob rm-rf /etc/ssh/ssh_host_*
+if [ $NICs_count -eq 0 ]; then
+ echo -e "\tNo NIC to configure. Strange! Exiting."
+ echo "rm -f /temp/configure" >> ./RC-FILE
+ exit 0
+fi
 
-
-echo -e " Clear the resolv.conf file"
-upload -<<END /etc/resolv.conf
+for i in `seq 1 $NICs_count`
+do
+ if [ $i -eq 1 ];then
+ if [[ "@NIC1.ipaddress@" =~ [0-9]*\.[0-9]*\.[0-9]*\.[0-9]* ]]; then
+ echo "sh /temp/NIC-configure @NIC1.mac@ @NIC1.vlanid@ @NIC1.ipaddress@ @NIC1.gateway@ @NIC1.domain@ @NIC1.dns1@ @NIC1.dns2@ @NIC1.netmask@" >> ./RC-FILE
+ else
+ echo "sh /temp/NIC-configure @NIC1.mac@ @NIC1.vlanid@" >> ./RC-FILE
+ fi
+ elif [ $i -eq 2 ];then
+ if [[ "@NIC2.ipaddress@" =~ [0-9]*\.[0-9]*\.[0-9]*\.[0-9]* ]]; then
+ echo "sh /temp/NIC-configure @NIC2.mac@ @NIC2.vlanid@ @NIC2.ipaddress@ @NIC2.gateway@ @NIC2.domain@ @NIC2.dns1@ @NIC2.dns2@ @NIC2.netmask@" >> ./RC-FILE
+ else
+ echo "sh /temp/NIC-configure @NIC2.mac@ @NIC2.vlanid@" >> ./RC-FILE
+ fi
+ elif [ $i -eq 3 ];then
+ if [[ "@NIC3.ipaddress@" =~ [0-9]*\.[0-9]*\.[0-9]*\.[0-9]* ]]; then
+ echo "sh /temp/NIC-configure @NIC3.mac@ @NIC3.vlanid@ @NIC3.ipaddress@ @NIC3.gateway@ @NIC3.domain@ @NIC3.dns1@ @NIC3.dns2@ @NIC3.netmask@" >> ./RC-FILE
+ else
+ echo "sh /temp/NIC-configure @NIC3.mac@ @NIC3.vlanid@" >> ./RC-FILE
+ fi
+ elif [ $i -eq 4 ];then
+ if [[ "@NIC4.ipaddress@" =~ [0-9]*\.[0-9]*\.[0-9]*\.[0-9]* ]]; then
+ echo "sh /temp/NIC-configure @NIC4.mac@ @NIC4.vlanid@ @NIC4.ipaddress@ @NIC4.gateway@ @NIC4.domain@ @NIC4.dns1@ @NIC4.dns2@ @NIC4.netmask@" >> ./RC-FILE
+ else
+ echo "sh /temp/NIC-configure @NIC4.mac@ @NIC4.vlanid@" >> ./RC-FILE
+ fi
+ fi
+done
+echo "systemctl restart network " >> ./RC-FILE
+echo "rm -f /temp/NIC-configure" >> ./RC-FILE
+exit 0
 END
+
+# The following echo command is executed by the guestfish shell.
+# Its output goes in the OS-Volume Activity log file.
+echo "\tLaunch the network-configuration script and populate the RC file"
+
+# The following command copies-out the above script into the Image Streamer.
+download /temp/ImageStreamer/network-configuration ./network-configuration
+
+# The following command asks the Image Streamer to execute the above script.
+!source ./network-configuration
diff --git a/src/Linux-configure-users-Deploy-FDZ b/src/Linux-configure-users-Deploy-FDZ
--- a/src/Linux-configure-users-Deploy-FDZ
+++ b/src/Linux-configure-users-Deploy-FDZ
@@ -1,6 +1,6 @@
 # ############################################
-# Linux-generalize-network-Capture-FDZ
-# Version: 0.5
+# Linux-configure-users-Deploy-FDZ
+# Version: 0.4
 #############################################
 # (c) Copyright 2017 Hewlett Packard Enterprise Development LP
 #
@@ -13,84 +13,124 @@
 # CONDITIONS OF ANY KIND, either express or implied. See the License for the
 # specific language governing permissions and limitations under the License.
 
-#The output of the following guestfish echo commands goes
-# into the Golden Image Activity log file.
+# The output of the following 4 guestfish echo commands goes
+# in the OS-Volume Activity log file.
 echo "======================================="
-echo "Linux-generalize-network-Capture-FDZ"
+echo "Linux-configure-users-Deploy-FDZ"
 echo "======================================="
+echo "\tPrepare sript to change root's password during next reboot"
 
-# Create a temporary directory in the Image Streamer
-!mkdir new_network
+# The following bash script is written in the OS-Volume
+# /temp/change_root_passwd file. It will be executed by 
+# RC-FILE during next reboot.
+upload -<<END /temp/change_root_passwd
+#! /bin/bash
+# The following echo commands write the name of this script
+# in the OS log file. Typically /var/log/messages.
+echo "Entering ${0}..."
 
+# Retrieve OS-Type and set OS-Type dependent variables.
+OS_Type=$(cat /temp/OS-Type)
 
-# The output of the following guestfish command goes
-# in the Golden Image Activity log file.
-echo " Copy out the network directory"
-
-# Depending on the OS-Type, push-out the entire network directory
-# to the just created new_network directory in the Image Streamer.
-<!awk '/sles/ {print "copy-out /etc/sysconfig/network/ new_network/"} ; /rhel/ || /centos/ || /xen/ {print "copy-out /etc/sysconfig/network-scripts new_network/"}' ./OS-Type
-
-# Create a bash script in the Golden Image that will be 
-# pushed-out to the Image Streamer before execution.
-upload -<<END /temp/ImageStreamer/gen_network_conf 
-#!/bin/bash
-
-OS_Type=$(cat OS-Type)
 case $OS_Type in
- rhel|centos|xen*)
- NET_DIR="network-scripts"
+ rhel|centos)
+ # ToDo: it may be possible to use chpasswd as in SLES...
+ echo "@NewRootPassword@" | passwd root --stdin
  ;;
  sles)
- NET_DIR="network"
+ echo "root:@NewRootPassword@" | chpasswd
  ;;
  *)
- echo "OS Type $OS_Type not supported. Exiting. " 
- exit 1 
+ echo "OS Type not supported. Exiting. "
+ exit 1
  ;;
 esac
- 
-net_cfg_files=`ls new_network/$NET_DIR/ | grep "ifcfg-"`
+echo "Exiting ${0}..."
 
-for net_cfg_file in $net_cfg_files
+# The following command delete the current script.
+unlink $0
+END
+
+# The output of the following echo commands goes
+# in the OS-Volume Activity log file.
+echo "\tPrepare /temp/add_users script to add new user(s)"
+echo "\tand set their password."
+
+# The following script will be executed by the RC file
+# during the next reboot (see below).
+upload -<<END /temp/add_users
+#!/bin/bash
+
+# The following echo commands prints the name of
+# this script in the OS log file. Typically /var/log/messages.
+echo "Entering ${0}..."
+
+# Retrieve OS-Type and set OS-Type dependent variables.
+OS_Type=$(cat /temp/OS-Type)
+
+echo "Add comment in /etc/{group,passwd}"
+# Add comments in passwd and group files to delimit the start of Image Streamer modifications
+[[ "$OS_Type" == "rhel" || "$OS_Type" == "centos" ]] && sed -i -e '$a\#START of Image Streamer modifications' /etc/group
+sed -i -e '$a\#START of Image Streamer modifications' /etc/passwd
+
+# The following variable contains the list of the 
+# new users to create, separated by a comma (,) or a semi-colon (;).
+users_string="@NewUsers@"
+
+#Users will be added with the same password. On first login users will have to change their password.
+password="@NewUsersPassword@"
+IFS=',; ' read -r -a array <<< "$users_string"
+for user in "${array[@]}"
 do
-	if [ $net_cfg_file != "ifcfg-lo" ]
-	then
-		rm -rf new_network/$NET_DIR/$net_cfg_file 
-		echo -e "\tNetwork interface cfg file $net_cfg_file successfully removed!!!" 
+	if [ $(id -u) -eq 0 ]; then
+			egrep "$user" /etc/passwd >/dev/null
+			if [ $? -eq 0 ]; then
+					echo "Warning: $user exists!"
+			else
+ case $OS_Type in 
+ rhel|centos)
+					 useradd -m $user
+					 chage -d 0 $user
+					 # ToDo: it may be possible to use chpasswd as in SLES...
+ # echo $password | passwd $user --stdin
+ echo "$user:$password" | chpasswd 
+					 [ $? -eq 0 ] && echo "User $user has been added to system!" || echo "Failed to add a user!"
+ ;;
+ sles)
+ useradd -m $user
+ echo "$user:$password" | chpasswd
+ [ $? -eq 0 ] && echo "User $user has been added to system!" || echo "Failed to add a user!"
+ ;;
+ *)
+ echo "OS Type: $OS_TYPE not supported. Exiting."
+ exit 1
+ ;;
+ esac
+
+			fi
+	else
+			echo "Error: Unable to add $user"
+ exit 2
 	fi
 done
-exit 0
+
+# Add comments in passwd file to delimit the end of Image Streamer modifications:
+sed -i -e '$a\#END of Image Streamer modifications' /etc/passwd
+[[ "$OS_Type" == "rhel" || "$OS_Type" == "centos" ]] && sed -i -e '$a\#END of Image Streamer modifications' /etc/group
+
+# The outuput of the following shell command goes
+# in the OS log file. Typically /var/log/messages.
+echo "Exiting ${0}..."
+
+# Delete this script from the OS-Volume temporary directory.
+unlink $0
 END
 
-# Push-out the above script before execution in the Image Streamer
-download /temp/ImageStreamer/gen_network_conf ./gen_network_conf
-!source ./gen_network_conf
+# The output of the following echo command goes in 
+# the OS-Volume Activity log file.
+echo "\tAdd change_root_passwd and add_users scripts to RC file to run at boot time."
 
-# The output of the following guestfish echo command goes
-# in the Golden Image Activity log file.
-echo " Removal of the Golden Image network directory"
-
-# Remove the Golden Image network directory 
-# depending on the OS-Type.
-<!awk '/sles/ {print "rm-rf /etc/sysconfig/network"} ; /rhel/ || /centos/ || /xen/ {print "rm-rf /etc/sysconfig/network-scripts"}' ./OS-Type
-
-# Pull-in the cleaned network directory into the Golden Image
-# at the right location depending on the OS-Type.
-echo " Pull-in the cleaned network directory into the Golden Image" 
-<!awk '/sles/ {print "copy-in new_network/network/ /etc/sysconfig/ "} ; /rhel/ || /centos/ || /xen/ {print "copy-in new_network/network-scripts/ /etc/sysconfig"}' ./OS-Type
-
-
-# Various clean up in the Golden Image.
-# The output of the guestfish echo commands goes
-# in the Golden Image Activity log file.
-echo " Remove /etc/init.d/ibftT if exists"
--rm-rf /etc/init.d/ibftT
-
-echo " Remove SSH host keys"
--glob rm-rf /etc/ssh/ssh_host_*
-
-
-echo -e " Clear the resolv.conf file"
-upload -<<END /etc/resolv.conf
-END
+# The following Image Streamer commands append lines
+# in the RC file already present in the Image Streamer.
+!echo "sh /temp/change_root_passwd" >> ./RC-FILE
+!echo "sh /temp/add_users" >> ./RC-FILE
